### PR TITLE
Add sync setting (not tested)

### PR DESCRIPTION
**Pull request by matthuisman**
@Dis90 

as per: https://github.com/Dis90/plugin.video.discoveryplus/issues/30

quick PR that should work.
Not tested as I don't have a login

### CODE REVIEW

**Comment by Dis90** [comment]
Thanks for PR. Can you make changes also to line 1916 https://github.com/Dis90/plugin.video.discoveryplus/blob/cf6a870c75ebe4a05b66fc0f47605f849959005c/addon.py#L1916

**Comment by matthuisman** [comment]
I'll update soon (just putting 1 year old to bed). One other small tweak as well as what you pointed out

**Comment by matthuisman** [comment]
ok, should be good to go now. I decided against the other tweak :)

**Comment by Dis90** [comment]
Tested and works :)

**Pull request merged**
