### PR TITLE
use hls proxy for d+ us

### PR DESCRIPTION
**Pull request by yeahme49**

### CODE REVIEW

**Comment by Dis90** [comment]
Looks good to me. Do we need backport for Kodi 18 version of addon?

**Comment by yeahme49** [comment]
Probably wouldn't be a bad idea to backport. I think all the code will work on Kodi18 as is so shouldn't need any changes

**Comment by Dis90** [comment]
Can you please make backport? :)

**Comment by yeahme49** [comment]
PR submitted for leia

**Comment by yeahme49** [comment]
updated to a more simple proxy

**Pull request merged**
